Last active date
sourcecodeschool/source-code pull request #19
Opened 2020-07-15 11:51 UTC by ZuffZuff

2020-07-15 14:47 UTC, sourcecodeschool commented on src/main/java/ru/javacourse/sourcecodebot/model/User.java
> +    private LocalDate lastActiveDate;
Возьми лучше LocalDateTime, чтобы была так же привязка ко времени

2020-07-15 14:49 UTC, sourcecodeschool requested changes

2020-07-15 14:49 UTC, sourcecodeschool commented on src/main/java/ru/javacourse/sourcecodebot/telegram/ServiceBot.java
> +                userRepository.setUserLastActiveDate(LocalDate.now(), optUser.get().getUserId());
можно сделать гораздо проще - просто присваивай юзеру дату и делай save

2020-07-16 10:41 UTC, ZuffZuff commented on src/main/java/ru/javacourse/sourcecodebot/model/User.java
> +    private LocalDate lastActiveDate;
Готово

2020-07-16 10:42 UTC, ZuffZuff commented on src/main/java/ru/javacourse/sourcecodebot/telegram/ServiceBot.java
> +                userRepository.setUserLastActiveDate(LocalDate.now(), optUser.get().getUserId());
Поправил, лишнее убрал

2020-07-19 16:34 UTC, sourcecodeschool approved these changes

2020-07-19 16:34 UTC, merged